#!/bin/bash

# Copyright (C) 2015  Jon Feldman/@chaoskagami
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>

# This file automatically fetches some 'known' files. In case of an api change, the files should
# be invalid.

SAVE=$(pwd)

cd ../src && source scangrab.nomain && cd $SAVE

# We override this. We don't want things zipped.
cbz_make() {
	CHECK_FLDR="$1"
	echo -ne "[Test] Checking $1..."
}

# We try to use SFW stuff for NSFW scrapers, fyi.

if [ "$1" = "" ]; then
	ALL=1
fi

# Okay as of July 14, 2015
if [ -f ../src/modules/fakku ]; then
	if [ ALL = 1 ] || [ "$1" = "fakku" ]; then
		source ../src/modules/fakku
		# Nagato Yuki. Non-H.
		dl_fakku "https://www.fakku.net/doujinshi/if-nagato-yuki-had-disappearances-personality-from-the-start-english"
		cd "${CHECK_FLDR}"
		if [ -e "../${CHECK_FLDR}.txt" ]; then
			sha512sum -c --quiet "../${CHECK_FLDR}.txt"
			R=$?
			if [ $R = 0 ]; then
				echo "OK!"
			else
				echo "Failed."
			fi
		fi
		cd ..
	fi
fi

# Okay as of July 14, 2015
if [ -f ../src/modules/eh ]; then
	if [ ALL = 1 ] || [ "$1" = "eh" ]; then
		source ../src/modules/eh
		# Natural Born Darkness. Seija doujin, Non-H. Had a good damn laugh.
		# Updated with a newer version (typo fix, apparently) on July 12, 2015
		dl_eh "http://g.e-hentai.org/g/824953/944e64d3e5/"
		cd "${CHECK_FLDR}"
		if [ -e "../${CHECK_FLDR}.txt" ]; then
			sha512sum -c --quiet "../${CHECK_FLDR}.txt"
			R=$?
			if [ $R = 0 ]; then
				echo "OK!"
			else
				echo "Failed."
			fi
		fi
		cd ..

	fi
fi

# These we know exist, but still test for existence anyways.

# Okay as of July 14, 2015
if [ -f ../src/modules/dynsc ]; then
	if [ ALL = 1 ] || [ "$1" = "dynsc" ]; then
		source ../src/modules/dynsc
		# Suika suika. Drunk.
		dl_dynsc "http://dynasty-scans.com/chapters/suika_suika"
		cd "${CHECK_FLDR}"
		if [ -e "../${CHECK_FLDR}.txt" ]; then
			sha512sum -c --quiet "../${CHECK_FLDR}.txt"
			R=$?
			if [ $R = 0 ]; then
				echo "OK!"
			else
				echo "Failed."
			fi
		fi
		cd ..
	fi
fi

# Okay as of July 14, 2015
if [ -f ../src/modules/batoto ]; then
	if [ ALL = 1 ] || [ "$1" = "batoto" ]; then
		source ../src/modules/batoto
		# Medaka Box ch1
		dl_batoto "http://bato.to/read/_/202832/medaka-box_v1_ch1_by_cxc-scans"
		cd "${CHECK_FLDR}"
		if [ -e "../${CHECK_FLDR}.txt" ]; then
			sha512sum -c --quiet "../${CHECK_FLDR}.txt"
			R=$?
			if [ $R = 0 ]; then
				echo "OK!"
			else
				echo "Failed."
			fi
		fi
		cd ..
	fi
fi

# Working as of July 14, 2015
if [ -f ../src/modules/mpark ]; then
	if [ ALL = 1 ] || [ "$1" = "mpark" ]; then
		source ../src/modules/mpark
		# New Game. It's new-ish and kinda funny.
		dl_mpark "http://mangapark.me/manga/new-game-tokunou-shoutarou/s1/v1/c1"
		cd "${CHECK_FLDR}"
		if [ -e "../${CHECK_FLDR}.txt" ]; then
			sha512sum -c --quiet "../${CHECK_FLDR}.txt"
			R=$?
			if [ $R = 0 ]; then
				echo "OK!"
			else
				echo "Failed."
			fi
		fi
		cd ..

	fi
fi

# Okay as of July 14, 2015 (needs a few tweaks tho)
if [ -f ../src/modules/foolsl ]; then
	if [ ALL = 1 ] || [ "$1" = "foolsl" ]; then
		source ../src/modules/foolsl
		# The canonical test is Seitokai Yakuindomo; and these guys coded foolslide, so yeah.
		dl_foolsl "http://foolrulez.org/slide/reader/read/seitokai_yakuindomo/en/1/1/"
		# We can't test the 'gimme zip' download...
		echo "Can't test. This is expected."
	fi
fi

# Spinner.
if [ "$1" = "spinner" ]; then
	MAX=20
	ADJ=4
	echo -ne "[Test] Spinner test... "
	ON=1
	for (( spinc = 0 ; spinc < MAX ; spinc++ )); do
		spinner "$spinc / $MAX"
		sleep 3
		if [ $ON = 1 ]; then
			message="AAAAA"
			ON=0
		else
			message="b"
			ON=1
		fi
	done
	spinner_done
fi
