#!/bin/bash

function auto_dynsc() {
	if [ -n "`echo $1 | grep 'dynasty-scans.com/' | sed -e 's/^ *//' -e 's/[[:space:]]*$//'`" ]; then
		# Dynasty Scans.
		dl_dynsc "$1"
	fi
}

function dl_dynsc() {
	
	# Now loop-de-loop. First, make a decent name. Dynasty always has
	# a short-title at the end of the URL.

	folder="`echo $1 | sed -re 's/^.+\///'`"
	mkdir -p $folder
	cd $folder

	PAGEDATA=`wget --quiet $1 -O - | grep "var pages" -`

	# This set of seds cuts up the pagelist in a manner
	# that makes it identical to a bash array.
	# So we're essentially modifying the webpage into a dl-script.
	# Cool, eh?

	PAGETMP=`echo $PAGEDATA | sed -e "s/\"image\"\://g" | sed -e "s/,\"name\"\:\"[[:alnum:]_-]*\"//g" | sed -e "s/\}\]/\)/g" | sed -e "s/{//g" | sed -e "s/}//g" | sed -e "s/;//g" | sed -e "s/ //g" | sed -e "s/varpages=\[/pages=\(/g" | sed -e "s/,/ /g"`

	# One possible nasty. Spaces.
	# sed -i "s/\%20/ /g" tmp.1

	# Load in the array.
	eval $PAGETMP

	echo -n "[DynastyScans] Downloading '$folder' "

	for image in "${pages[@]}"; do
		wget --no-cache -nc -t 0 -w 30 "http://dynasty-scans.com$image" > /dev/null 2>&1
		spinner
	done

	done_spin
	
	cd ..

	cbz_make $folder
}
