#!/bin/bash

# Unlike all of the other plugins, this is a generic downloader for foolslide based sites.
# Therefore, instead of keeping it a generic and needing to specifically ask for this plugin,
# I use a compatibility list.
# Sites using foolslide:
#   reader.vortex-scans.com
#   foolrulez.org

function auto_foolsl() {
	if [ -n "`echo $1 | grep 'foolrulez.org/' | sed -e 's/^ *//' -e 's/[[:space:]]*$//'`" ]; then
		# FoolRulez
		return 1
	elif [ -n "`echo $1 | grep 'vortex-scans.com/' | sed -e 's/^ *//' -e 's/[[:space:]]*$//'`" ]; then
		# VortexScans
		return 1
	fi

	return 0
}

function dl_foolsl() {
	# Attempt a lazy download first. Only image scrape if rejected.

	LAZYURL=`echo $1 | sed "s|/read/|/download/|g"`

	echo -n "[FoolSlide] Attempting Lazy Download "

	FAILED=0

	wget --content-disposition --no-cache -nc -t 0 -w 30 "$LAZYURL" > /dev/null 2>&1 || export FAILED=1

	if [ $FAILED == 1 ]; then
		echo "[FAIL]"
		echo "[Foolslide] Downloading via alternate method "
	else
		echo "[OK]"
	fi
}

function scrape_foolsl() {

	echo -n "[Foolslide] Scraping Chapters..."

	wget --no-cache -nc -t 0 -w 30 "$1" -O tmp.htm

	grep '<div class="title"><a href=' tmp.htm > batch.txt
	
	sed -i 's|<div class="title"><a href="||g' batch.txt
	sed -i 's|" title=.*||g' batch.txt
	sed -i "s/^[[:space:]]*//" batch.txt
	sed -i "s/[[:space:]]*$//" batch.txt
	
	echo -e "\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b[Foolslide] Scraped chapters to batch.txt. You can modify this, or pass it to autobatch."
}
