#!/bin/bash
# Copyright (C) 2015  Jon Feldman/@chaoskagami
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>

imgur_longname="Imgur Gallery"
imgur_url="imgur.com/"
imgur_state=1
# No filter
imgur_filt=0

auto_imgur() {
	if [ -n "`echo $1 | grep 'imgur.com/a/' | sed -e 's/^ *//' -e 's/[[:space:]]*$//'`" ]; then
		# Imgur.
		return 1
	fi

	return 0
}

dl_imgur() {

	# Now loop-de-loop. First, make a decent name. Dynasty always has
	# a short-title at the end of the URL.

	PAGEDATA="$(fetch "$1" "-")"

	folder="$(echo "$PAGEDATA" | grep "</title>" | sed -e 's|<title>||g' -e 's/^[[:space:]]*//g' -e 's|</title>||g' | sed 's| - Album on Imgur||g')"

	is_done "$folder"
	R=$?
	if [ $R = 1 ]; then
		echo "[Imgur] Already downloaded. Skipping."
		return 0
	fi

	mkdir -p "$folder"
	cd "$folder"

	declare -a PAGELIST
	PAGELIST=($(echo "$PAGEDATA" | grep '<meta property="og:image"' | sed -e 's|^.*content="||g' -e 's|".*$||g' -e '/?fb/d'))

	echo -n "[Imgur] Downloading '$folder' "

	CUR=0

	for image in "${PAGELIST[@]}"; do
		EXT=$(echo "$image" | sed 's|.*\.||g')
		fetch "$image" "${CUR}.${EXT}"
		spinner "$CUR"
		CUR=$(( CUR + 1 ))
	done

	spinner_done

	cd ..

	cbz_make "$folder"
}

scrape_imgur() {
	echo -n ""
}



