#!/bin/bash
# Copyright (C) 2015  Jon Feldman/@chaoskagami
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>

# NiconicoSeiga is odd in that an account is required. Therefore, I had to implement cookiejars.

niconicoseiga_longname="Niconico Seiga"
niconicoseiga_url="seiga.nicovideo.jp"
niconicoseiga_state=1
niconicoseiga_filt=0
niconicoseiga_note="Please login first."

# Need to login.
niconicoseiga_uselogin=1

auto_niconicoseiga() {
	if [ -n "`echo $1 | grep 'seiga.nicovideo.jp' | sed -e 's/^ *//' -e 's/[[:space:]]*$//'`" ]; then
		# Niconico Seiga
		return 1
	fi

	return 0
}

login_niconicoseiga() {
	use_cookies=1
	s_login "mail_tel" "password" "$1" "$2" "https://secure.nicovideo.jp/secure/login"
}

dl_niconicoseiga() {
	use_cookies=1

	TEMP="$(temp f)"

	fetch $1 "$TEMP"

	fullname="$(cat "$TEMP" | grep '<meta property="og:title" content="' | sed -e 's|<meta property="og:title" content="||g' -e "s|\".*||g" | entity_to_char | remove_illegal)"

	if [ ! -f "$TEMP" ]; then
		message "No page found, aborting."
		return 1
	fi

	message "Extracting image list..."

	TEMP2="$(temp f)"

	cat "$TEMP" | grep 'data-image-id' | sed -e 's|^[[:space:]]*data-image-id="||g' -e 's|"[[:space:]]*$||g' > "$TEMP2"

	if [ "$(cat "$TEMP2")" = "" ]; then
		message "No images in page. Did you login?"
		return 1
	fi

	is_done "$folder"
	R=$?
	if [ $R = 1 ]; then
		message "Already downloaded. Skipping."
		return 0
	fi

	mkdir -p "$fullname"
	cd "$fullname"

	message "Downloading '$fullname' (from $name) "

	COUNT=0
	while read ID; do
		COUNT=$((COUNT + 1))
		fetch "http://lohas.nicoseiga.jp/thumb/${ID}p" "${COUNT}.jpg"
		spinner $COUNT
	done < "../$TEMP2"

	spinner_done

	cd ..
	rm "$TEMP" "$TEMP2"

	cbz_make "$fullname"
}

scrape_niconicoseiga() {
	COOKIES=1

	message "Scraping chapters..."

	fetch "$1" "-" | grep 'class="episode"' | sed -e 's|.*<a href="||g' -e 's|?.*||g' -e 's|/watch|http://seiga.nicovideo.jp/watch|g' >> batch.txt

	message "Done."
}
