#!/bin/bash

# Copyright (C) 2015  Jon Feldman/@chaoskagami
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#

auto() {
	for module in ${MODS[@]}; do
		auto_${module} "$@"
		RETCHECK=$?
		if [ $RETCHECK = 1 ]; then
			MODULE_NAME=$(eval echo \$${module}_longname)
			dl_${module} "$@"
			return 0
		fi
	done
	MODULE_NAME="Generic"
	dl_generic "$@"
	return 0
}
