#!/bin/bash

# Copyright (C) 2015  Jon Feldman/@chaoskagami
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#

batch() {
	# $2 is a file. Read it in line by line as $1 and $2.
	while read chunk; do
		$0 $chunk
	done < $1
}
