#!/bin/bash

# Copyright (C) 2015  Jon Feldman/@chaoskagami
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#

mod_login() {
	for module in ${MODS[@]}; do
		if [ "$1" = "$module" ]; then
			MODULE_NAME=$(eval echo \$${module}_longname)
			if [ "$( eval echo \$${module}_uselogin )" = "1" ]; then
				echo -ne "[${MODULE_NAME}] Username: "
				read username

				echo -ne "[${MODULE_NAME}] Password for $username (will not echo): "
				read -s password

				login_${module} "$username" "$password"
				exit 0
			else
				echo "$module does not need login."
				exit 0
			fi
		fi
	done
	echo "No such module."
	exit 1
}
