#!/bin/bash

# Copyright (C) 2015  Jon Feldman/@chaoskagami
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#

upgrade_self() {
	if [ "$type" = "repo" ]; then
		echo "[Upgrade] You're in a git repo. Use 'git pull' instead."
		exit 0
	fi
	URL="https://raw.githubusercontent.com/chaoskagami/scangrab/$branch/dist/scangrab.$type"
	echo "[Upgrade] Checking this scangrab's sha256sum..."
	this_sha256="$( cat "${0}" | sha256sum )"
	fetch_no_ops "${URL}.sha256sum" new.sha256sum
	gith_sha256="$( cat new.sha256sum )"

	echo "[Upgrade] Local:  $this_sha256"
	echo "[Upgrade] Github: $gith_sha256"

	if [ "$this_sha256" = "$gith_sha256" ]; then
		echo "[Upgrade] Not required. Same sha256 as upstream."
		exit 0
	else
		echo "[Upgrade] Doesn't match upstream. Fetching..."
		fetch_no_ops "$URL" "${0}.new"
		R=$?
		if [ ! $R = 0 ]; then
			echo "[Upgrade] Fetch failed. Error code: $R. Do you have write permission?"
			exit $R
		fi
		echo "[Upgrade] Downloaded replacement. Checking replacement's sha256sum..."
		new_sha256="$( cat "${0}.new" | sha256sum )"
		echo "[Upgrade] Replacement: $new_sha256"
		if [ "$new_sha256" = "$gith_sha256" ]; then
			echo "[Upgrade] Matched. Replacing self..."
			cp -f "${0}.new" "${0}"
			R=$?
			if [ ! $R = 0 ]; then
				echo "[Upgrade] Couldn't replace. cp error: $R. Abort."
				rm "${0}.new"
				exit $R
			fi
			echo "[Upgrade] Sync to avoid race conditions..."
			sync
			echo "[Upgrade] Checking to make sure it has been replaced..."
			new_sha256="$(cat "${0}" | sha256sum )"
			if [ ! "$new_sha256" = "$gith_sha256" ]; then
				echo "[Upgrade] Sanity check failed. This is not normal."
				exit 1;
			fi
			echo "[Upgrade] Succeeded. Exiting."
			exit 0
		else
			echo "[Upgrade] Failed. sha256 does not match."
		fi
	fi
	exit 1
}
