#!/bin/bash

# Copyright (C) 2015  Jon Feldman/@chaoskagami
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#

upgrade_self() {
	if [ "$type" = "repo" ]; then
		echo "[Upgrade] You're in a git repo. Use 'git pull' instead."
		exit 0
	fi
	URL="https://raw.githubusercontent.com/chaoskagami/scangrab/$branch/dist/scangrab.$type"
	echo "[Upgrade] Checking this scangrab's sha256sum..."
	this_sha256="$(cat "$0" | sha256sum - | sed "s| .*||g")"
	gith_sha256="$(fetch "$URL.sha256sum" "-" | sed "s| .*||g")"

	echo "[Upgrade] Local:  $this_sha256"
	echo "[Upgrade] Github: $gith_sha256"

	if [ "$this_sha256" = "$gith_sha256" ]; then
		echo "[Upgrade] Not required. Same sha256 as upstream."
		exit 0
	else
		echo "[Upgrade] Doesn't match upstream. Fetching..."
		fetch "$URL" "$0"
		R=$?
		if [ ! $R = 0 ]; then
			echo "[Upgrade] Fetch failed. Error code: $R. Do you have write permission?"
			exit $R
		fi
		echo "[Upgrade] We appear to have replaced ourselves. Checking sha256..."
		this_sha256="$(cat "$0" | sha256sum - | sed "s| .*||g")"
		if [ "$this_sha256" = "$gith_sha256" ]; then
			echo "[Upgrade] Succeded."
		else
			echo "[Upgrade] Failed. sha256 does not match github."
		fi
	fi
}
