#!/bin/bash

# Copyright (C) 2015  Jon Feldman/@chaoskagami
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#

entity_to_char() {
	# This probably doesn't handle every case. It should be enough.
	# It also handles the case of illegal characters on windows/FAT/NTFS.
	# And the case of a slash in the name which is the only illegal one on linux.

	# Always put 0* before any number, since some pages have &#039, for example.

	sed                     \
		-e "s/&#0*32;/ /g"    \
		-e "s/&nbsp;/ /g"   \
		-e "s/&#0*33;/\!/g"   \
		-e "s/&#0*34;/\"/g"   \
		-e "s/&quot;/\"/g"   \
		-e "s/&#0*35;/\#/g"   \
		                    \
		-e "s/&#0*36;/\$/g"   \
		-e "s/&#0*37;/\%/g"   \
		-e "s/&amp;/\&/g"   \
		-e "s/&#0*38;/\&/g"   \
		-e "s/&#0*39;/'/g"    \
		                    \
		-e "s/&#0*40;/\(/g"   \
		-e "s/&#0*41;/\)/g"   \
		-e "s/&#0*42;/\*/g"   \
		-e "s/&#0*43;/\+/g"   \
		-e "s/&#0*44;/\,/g"   \
		                    \
		-e "s/&#0*45;/\-/g"   \
		-e "s/&#0*46;/\./g"   \
		-e "s/&#0*58;/\:/g"   \
		-e "s/&#0*59;/\;/g"   \
		-e "s/&lt;/\</g"    \
		                    \
		-e "s/&#0*60;/\</g"   \
		-e "s/&gt/\>/g"     \
		-e "s/&#0*61;/\>/g"   \
		-e "s/&#0*63;/\?/g"   \
		-e "s/&#0*64;/\@/g"   \
		                    \
		-e "s/&#0*91;/\[/g"   \
		-e "s/&#0*92;/\\\\/g" \
		-e "s/&#0*93;/\]/g"   \
		-e "s/&#0*94;/\^/g"   \
		-e "s/&#0*95;/\_/g"   \
		                    \
		-e "s/&#0*123;/\{/g"  \
		-e "s/&#0*124;/\|/g"  \
		-e "s/&#0*125;/\}/g"  \
		-e "s/&#0*126;/\~/g"  \
		-e "s/&yen;/¥/g"    \
		                    \
		-e "s/&#0*165;/¥/g"   \
		-e "s/&sup2;/²/g"   \
		-e "s/&#0*178;/²/g"   \
		-e "s/&sup3;/³/g"   \
		-e "s/&#0*179;/³/g"   \
		                    \
		-e "s/&frac14;/¼/g" \
		-e "s/&#0*188;/¼/g"   \
		-e "s/&frac12;/½/g" \
		-e "s/&#0*189;/½/g"   \
		-e "s/&frac34;/¾/g" \
		                    \
		-e "s/&#0*190;/¾/g"   \
		-e "s/&spades;/♠/g" \
		-e "s/&#0*9824;/♠/g"  \
		-e "s/&clubs;/♣/g"  \
		-e "s/&#0*9827;/♣/g"  \
		                    \
		-e "s/&hearts;/♥/g" \
		-e "s/&#0*9829;/♥/g"  \
		-e "s/&diams;/♦/g"  \
		-e "s/&#0*9830;/♦/g"

}
