#!/bin/bash

# Copyright (C) 2015  Jon Feldman/@chaoskagami
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#

# These are characters that are either issue causing or
# not FAT-legal.

# Forward slash is not legal on linux.
# Pipe character isn't legal on FAT and can cause issues with redirection.
# ? is not FAT legal, so it is replaced with the unicode wide version
# Angle brackets are not FAT legal - they're replaced with parenthesis.
# \t is a no-no in filenames. I've seen at least one instance of this nastiness.
# \n - see \t.

remove_illegal() {

	sed \
		-e "s/|/-/g" \
		-e "s|/|-|g" \
		-e "s|?|？|g" \
		-e "s|<|(|g" \
		-e "s|>|)|g" \
		-e "s|\t| |g" \
		-e "s|\n| |g"
}
