#!/bin/bash

# Copyright (C) 2015  Jon Feldman/@chaoskagami
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#

# These are characters that are either issue causing or
# not FAT-legal.

remove_illegal() {

	sed \
		-e "s/|/-/g" \
		-e "s|/|-|g" \
		-e "s|?|？|g" \
		-e "s|<|(|g" \
		-e "s|>|)|g"

}
