#!/bin/bash

# Copyright (C) 2015  Jon Feldman/@chaoskagami
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#

spinner_done() {
	spinner_reset

	_MESG="OK"
	if [ ! "$1" = "" ]; then
		_MESG="$1"
	fi
	echo -e "[$_MESG]"
}
