#!/bin/bash

# Copyright (C) 2015  Jon Feldman/@chaoskagami
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>

# Determine operation.

fetch_detect

auto() {
	for module in ${MODS[@]}; do
		eval auto_$module $1
		RETCHECK=$?
		if [ $RETCHECK = 1 ]; then
			eval dl_$module $1
			exit 0
		fi
	done
}

batch() {
	# $2 is a file. Read it in line by line as $1 and $2.
	IFS=$'\n' read -d '' -r -a LINES < $1
	NEW=""
	for chunk in "${LINES[@]}"; do
		NEW="$NEW$0 $chunk ;"
	done
	eval $NEW
}

autobatch() {
	# $2 is a file. Read it in line by line as $1 and $2.
	IFS=$'\n' read -d '' -r -a LINES < $1
	NEW=""
	for chunk in "${LINES[@]}"; do
		NEW="$NEW$0 auto $chunk ;"
	done
	eval $NEW
}

scrape() {
	for module in ${MODS[@]}; do
		eval auto_$module $1
		RETCHECK=$?
		if [ $RETCHECK = 1 ]; then
			eval scrape_$module $1 $2
			exit 0
		fi
	done
}

mod_login() {
	for module in ${MODS[@]}; do
		if [ "$1" = "$module" ]; then
			if [ "$( eval echo \$${module}_loginreq )" = "1" ]; then
				eval login_$module \"$2\" \"$3\"
				exit 0
			else
				echo "$module does not need login."
				exit 0
			fi
		fi
	done
	echo "No such module."
	exit 1
}

help() {
	type 1
	echo -e "Usage:"
	type 0
	echo -ne "     $0     "
	color 3
	echo -ne "OPERATION     "
	color 5
	echo -e "[PARAMS]"
	type 0
	type 1
	echo -e "Operations:"
	type 0
	color 3
	echo -e "     auto (a)"
	type 0
	echo -e "          Chooses module based on URL"
	color 3
	echo -e "     batch (l)"
	type 0
	echo -e "          Takes a file with a list of types and URLs"
	color 3
	echo -e "     autobatch (b)"
	type 0
	echo -e "          Takes a file with URLs which will be run with auto."
	color 3
	echo -e "     scrape (s)"
	type 0
	echo -e "          Will take a manga's page and scrape chapters to"
	echo -e "          a file named batch.txt"
	color 3
	echo -e "     login (u)"
	type 0
	echo -e "          Pass the module name, your username and password."
	echo -e "          This will generate a cookie jar as ./cookiejar"
	echo ""
	echo -e "     You can also specify a module name followed by"
	echo -e "     the URL instead of using the auto-detect."
	echo ""
	echo -e "     If you don't specify an operation and pass only a URL"
	echo -e "     then we assume you want auto (a)."
	type 1
	echo -e "Download Modules:"
	type 0
	for mod in "${MODS[@]}"; do
		longname=$(temp=\$${mod}_longname && eval echo $temp)
		url=$(temp=\$${mod}_url && eval echo $temp)
		broke=$(temp=\$${mod}_state && eval echo $temp)
		filter=$(temp=\$${mod}_filt && eval echo $temp)
		note=$(temp=\$${mod}_note && eval echo $temp)

		echo -ne "     Module Name:                "
		color 3
		echo -e "$mod"

		type 0
		echo -ne "          Long Name:             "
		color 4
		echo -e "$longname"

		type 0
		echo -ne "          Site(s) Used with:     "
		color 5
		echo -e "$url"
		type 0

		type 0
		echo -ne "          Site(s) Current state: "
		if [ "$broke" = "1" ]; then
			color 2
			echo -e "Works"
		else
			color 1
			echo -e "Broken"
		fi

		if [ ! "$note" = "" ]; then
			type 0
			echo -e "          Site Note:             $note"
		fi

		type 0
		if [ "$filter" = "1" ]; then
			echo -e "          Supports filters for scrape"
		fi

		echo ""
	done
	type 1
	echo -e "Misc Info"
	type 0
	echo -e "     If you see an emote in the output, it means we had to deal"
	echo -e "     with a retrieval quirk."
	echo -e "\n     [ :/ ]       Given GZip'd data even though we said it wasn't"
	echo -e "                  supported in the GET."
	type 2
	echo -e "                  This happens frequently with batoto when doing"
	echo -e "                  multiple fetches. :/"
	type 0
	echo -e "\n     [ :( ]       Site didn't respond and so the DL failed"
	echo -e "                  We had to revert to a fallback method."

	echo -e "\n     [ >:( ]      Too many normal requests failed; we reverted"
	echo -e "                  to using entirely the fallback method."
	echo ""
	echo -e "     Some modules accept an extra parameter. Usually, this"
	echo -e "     is a filter. Try values like 'English' or 'French'."
	type 1
	echo -e "System Tools"
	type 0
	if [ ! "$_wget" = "" ]; then
		echo -e "     wget:                $_wget"
	fi
	if [ ! "$_curl" = "" ]; then
		echo -e "     curl:                $_curl"
	fi
	if [ ! "$_aria" = "" ]; then
		echo -e "     aria2c:              $_aria"
	fi
	echo -ne "     Will use:            "
	if [ $_FETCHTOOL = 1 ]; then
		echo -ne "wget"
		if [ $_BUSYBOX = 1 ]; then
			echo -ne ", busybox"
		else
			echo -ne ""
		fi
	elif [ $_FETCHTOOL = 2 ]; then
		echo -ne "curl"
	elif [ $_FETCHTOOL = 3 ]; then
		echo -ne "aria2c"
	else
		echo -ne "no tool. Install one of: "
	fi
	echo " (wget, curl, aria2c)"
	echo -ne "     Check broken images: "
	if [ $CHECK_VALID = 1 ]; then
		if [ -f $_identify ]; then
			echo -ne "imagemagick ($_identify)"
		fi
		echo ""
	else
		echo "no"
	fi
	echo -ne "     Color:               "
	if [ $COLOR = 1 ]; then
		color 1
		echo -ne "y"
		color 2
		echo -ne "e"
		color 3
		echo -ne "s"
		color 4
		echo -ne " "
		echo -ne "("
		color 5
		echo -ne "d"
		color 6
		echo -ne "u"
		color 1
		echo -ne "m"
		color 2
		echo -ne "b"
		color 3
		echo ")"
		type 0
	elif [ $COLOR = 2 ]; then
		color 1
		echo -ne "y"
		color 2
		echo -ne "e"
		color 3
		echo -ne "s"
		color 4
		echo -ne " "
		echo -ne "("
		color 5
		echo -ne "t"
		color 6
		echo -ne "p"
		color 1
		echo -ne "u"
		color 2
		echo -ne "t"
		color 3
		echo ")"
		type 0
	else
		echo "no (TERM='$TERM')"
	fi
	type 1
	echo -ne "License / Info"
	type 0
	echo ""
	echo -e "     Copyright (C) 2015     Jon Feldman/@chaoskagami"
	echo ""
	echo -e "     This program is free software: you can redistribute it and/or modify"
	echo -e "     it under the terms of the GNU General Public License as published by"
	echo -e "     the Free Software Foundation, either version 3 of the License, or"
	echo -e "     (at your option) any later version."
	echo ""
	echo -e "     This program is distributed in the hope that it will be useful,"
	echo -e "     but WITHOUT ANY WARRANTY; without even the implied warranty of"
	echo -e "     MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the"
	echo -e "     GNU General Public License for more details."
	echo ""
	echo -e "     You should have received a copy of the GNU General Public License"
	echo -e "     along with this program.  If not, see <http://www.gnu.org/licenses/>"
	echo ""
	echo -e "     The latest version of scangrab can always be found at the github"
	echo -e "     page here: https://github.com/chaoskagami/scangrab"
}

if [ "$1" = "auto" -o "$1" = "a" ]; then
	# Common operation - Automatic Module Select.
	auto $2 $3
elif [ "$1" = "batch" -o "$1" = "l" ]; then
	# Common operation - typed batch.
	batch $2 $3
elif [ "$1" = "autobatch" -o "$1" = "b" ]; then
	# Common operation - auto batch.
	autobatch $2 $3
elif [ "$1" = "scrape" -o "$1" = "s" ]; then
	# Link scraper.
	scrape $2 $3
elif [ "$1" = "login" -o "$1" = "u" ]; then
	# Site login.
	mod_login $2 $3 $4
else # Not a common operation - either invalid or a module-op.

	# Detect whether it is a module operation.

	MATCH=""

	for module in ${MODS[@]}; do
		if [ "$1" = "$module" ]; then
			MATCH="dl_$module $2"
		fi
	done

	if [ "$MATCH" = "" ]; then # All checks failed. Usage~
		if [ ! "$(echo "$1" | grep http)" = "" ]; then
			# URL as $1. Do auto.
			auto $1 $2
		else
			help
		fi
	else # Module operation.
		eval $MATCH
	fi
fi
