#!/bin/bash

# Copyright (C) 2015  Jon Feldman/@chaoskagami
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>

# Determine operation.

if [ "$1" = "auto" -o "$1" = "a" ]; then
	# Common operation - Automatic Module Select.
	shift
	auto "$@"
elif [ "$1" = "batch" -o "$1" = "l" ]; then
	# Common operation - typed batch.
	shift
	batch "$@"
elif [ "$1" = "autobatch" -o "$1" = "b" ]; then
	# Common operation - auto batch.
	shift
	autobatch "$@"
elif [ "$1" = "scrape" -o "$1" = "s" ]; then
	# Link scraper.
	shift
	scrape "$@"
elif [ "$1" = "login" -o "$1" = "u" ]; then
	# Site login.
	shift
	mod_login "$@"
elif [ "$1" = "upgrade" ]; then
	# Upgrade self.
	upgrade_self
else
	# Not a common operation - either invalid, a module, or a lazy URL.

	# Detect whether it is a module operation
	MATCH=""
	for module in ${MODS[@]}; do
		if [ "$1" = "$module" ]; then
			shift
			dl_${module} "$@"
			exit 0
		fi
	done

	# Try to see if this was a lazy URL as first parameter.
	auto "$@"

	# All checks failed. Usage~
	help
fi
