#!/bin/bash

# Copyright (C) 2015  Jon Feldman/@chaoskagami
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>

# Turn off history expansion. It only causes issues with exclamation points.
# TODO - this broke some shit. Fix it.
set +H

# Determine operation.

# New syntax; default is auto.
#  -b Batch download
#  -s Scrape list
#  -l Login
#  -U upgrade scangrab
#  -mModule Use module instead of detection.

CMD_STR="$1"
OPERATION=a
MODULE=a
TYPE=0
while [ "${CMD_STR:0:1}" = "-" ]; do
	if [ ${#CMD_STR} = 2 ]; then
		case ${CMD_STR:1:1} in
			b)
				OPERATION=b ;;
			s)
				OPERATION=s ;;
			l)
				OPERATION=l ;;
			U)
				OPERATION=U ;;
			u)
				usage
				exit 0
				;;
			h)
				help
				exit 0
				;;
			v)
				VERBOSE=1
				;;
			e)
				# This is used to import functions to a shell.
				# Not for general use.
				return 0 # cannot use exit - that would kill the shell
				;;
		esac
	elif [ "${CMD_STR:0:2}" = "-m" ]; then
		MODULE="${CMD_STR:2}"
		TYPE=1
	fi
	shift
	CMD_STR="$1"
done

if [ "$1" = "" ]; then
	echo "Invalid syntax. See usage (-u) or help (-h) for more info."
	exit 1
fi

case $OPERATION in
	a)
		if [ $TYPE = 0 ]; then
			auto "$@"
		else
			dl_$MODULE "$@"
		fi
		exit 0
		;;
	b)
		batch "$@"
		exit 0
		;;
	s)
		if [ $TYPE = 0 ]; then
			scrape "$@"
		else
			scrape_$MODULE "$@"
		fi
		exit 0
		;;
	l)
		if [ $TYPE = 0 ]; then
			echo "[scangrab] Please specify a module with the '-m' option."
			exit 1
		else
			mod_login "$MODULE"
		fi
		exit 0
		;;
	U)
		upgrade_self
		exit 0
		;;
esac
