#!/bin/bash

# Copyright (C) 2015  Jon Feldman/@chaoskagami
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>

# Why is this file separated? Because of minification.
# It allows merging files together.

# Load support code. A few common functions.

. ./rev

. ./support

# Load modules and index them.

MODS=($(find modules/ -maxdepth 1 -type f | sed 's|modules/||g'))

for module in ${MODS[@]}; do
	. modules/$module
done

# Run main code.

. ./main
