#!/bin/bash

# Copyright (C) 2015  Jon Feldman/@chaoskagami
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>

# This file is literally the 'load everything' file. It doesn't really
# do much work on its own. Merge generates it's own method of loading everything.

BASEDIR=$(pwd)

#@OVERRIDE_BASEDIR@

# The revision.
if [ -e "${BASEDIR}/.git" ] || [ -e "${BASEDIR}/../.git" ]; then
	save=$(pwd)
	cd "${BASEDIR}"
	eval $(git show | head -n1 | sed -e 's|commit |rev=|')
	eval $(git branch | grep '*' | sed -e 's|* |branch=|g')
	cd "$save"
else
	rev=unknown
	branch=unknown
fi

# Configure env.
. "${BASEDIR}/operations/configure_env"

# All misc functions (used to be support.)
OPERS=($(find "${BASEDIR}/operations/" -type f))
for script in ${OPERS[@]}; do
	source "${script}"
done

# All misc functions (used to be support.)
FUNCS=($(find "${BASEDIR}/functions/" -type f))
for script in ${FUNCS[@]}; do
	source "${script}"
done

# Load modules sources.
LIST=($(find "${BASEDIR}/modules/" -type f))
for script in ${LIST[@]}; do
	source "${script}"
done

# Export module names.
MODS=($(find "${BASEDIR}/modules/" -maxdepth 1 -type f | sed 's|.*/modules/||g'))

# Run main code.
. ${BASEDIR}/main
